#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-jeremymcanally-pending
Version  : 0.1
Release  : 3
URL      : https://rubygems.org/downloads/jeremymcanally-pending-0.1.gem
Source0  : https://rubygems.org/downloads/jeremymcanally-pending-0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-bones
BuildRequires : rubygem-rdoc
Patch1: 0001-Fix-gemspec.patch
Patch2: 0001-Modified-requirements-in-tests.patch

%description
pending
by Jeremy McAnally
http://jeremymcanally.com
== DESCRIPTION:
pending lets you define a block of test code that is currently "pending" functionality,
similar to RSpec's pending method.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n jeremymcanally-pending-0.1
gem spec %{SOURCE0} -l --ruby > rubygem-jeremymcanally-pending.gemspec
%patch1 -p1
%patch2 -p1

%build
gem build rubygem-jeremymcanally-pending.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
jeremymcanally-pending-0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/jeremymcanally-pending-0.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/jeremymcanally-pending-0.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/jeremymcanally-pending-0.1/ri/page-History_txt.ri
/usr/lib64/ruby/gems/2.2.0/doc/jeremymcanally-pending-0.1/ri/page-README_txt.ri
/usr/lib64/ruby/gems/2.2.0/gems/jeremymcanally-pending-0.1/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/jeremymcanally-pending-0.1/README.txt
/usr/lib64/ruby/gems/2.2.0/gems/jeremymcanally-pending-0.1/test/test_pending.rb
/usr/lib64/ruby/gems/2.2.0/specifications/jeremymcanally-pending-0.1.gemspec
